# generated by hwacha-cc from pfvar/A.ll
# ---- worker threads (vector-fetch blocks) ----

    .text
    .align 3
    .globl dynproc_kernel_wt
dynproc_kernel_wt:
    vpset vp0
    veidx vv0
    vpclear vp1
    vsllw vs1, vs58, vs57
    vmulw vs1, vs1, vs56
    vsubw vs1, vs63, vs1
    vmulw vs1, vs1, vs62
    vsubw vs1, vs1, vs55
    vaddw vs2, vs1, vs63
    vaddw vv5, vs1, vv0
    vaddw vv6, vs1, vs0
    vcmplt vp2, vv6, vs0
    @vp2 vaddw vs1, vv6, vs0
    @!vp2 vaddw vs1, vs0, vs0
    vsubw vs1, vs0, vs1
    vaddw vv6, vs54, vs0
    vcmplt vp2, vv6, vs2
    vaddw vs3, vs63, vs53
    @vp2 vsubw vs4, vs54, vs2
    @!vp2 vaddw vs4, vs0, vs0
    vaddw vs3, vs3, vs4
    vaddw vv6, vv0, vs53
    vcmplt vp2, vv6, vs1
    @vp2 vaddw vv6, vs1, vs0
    @!vp2 vaddw vv6, vv6, vs0
    vcmplt vp2, vv0, vs1
    vpop vp2, vp2, vp2, vp2, 0x55
    vcmplt vp3, vs3, vv0
    vpop vp3, vp3, vp3, vp3, 0x55
    vcmplt vp4, vs53, vv5
    vcmplt vp5, vv5, vs54
    vpop vp4, vp4, vp5, vp4, 136
    vpop vp5, vp0, vp4, vp4, 0x80
    vpop vp6, vp0, vp4, vp4, 0x02
    @!vp5 vcjal 0, vs1, .Ldynproc_kernel_skip0
    vsll vv1, vv5, vs47
    vsrl vv1, vv1, vs47
    @vp5 vsll vv1, vv1, vs52
    @vp5 vlxw vv7, vs60, vv1
    @vp5 vsw vv7, va0
.Ldynproc_kernel_skip0:
    vpop vp4, vp5, vp5, vp5, 0xAA
    vpop vp4, vp4, vp6, vp6, 0xEE
    @!vp4 vcjal 0, vs1, .Ldynproc_kernel_skip1
    vfence
    vaddw vv7, vs0, vs0
    vcmplt vp5, vv7, vs58
.Ldynproc_kernel_skip1:
    vpop vp6, vp4, vp5, vp5, 0x80
    vpop vp7, vp4, vp5, vp5, 0x02
    @!vp6 vcjal 0, vs1, .Ldynproc_kernel_skip2
    vaddw vs2, vs63, vs51
    vsll vv1, vv6, vs47
    vsrl vv1, vv1, vs47
    vaddw vs4, vs58, vs53
    vsll vs4, vs4, vs47
    vsrl vs4, vs4, vs47
    @vp6 vsll vv1, vv1, vs52
    @vp6 vadd vv2, vv0, vs49
    vcmplt vp4, vv2, vs3
    @vp4 vadd vv2, vv2, vs0
    @!vp4 vadd vv2, vs3, vs0
    @vp6 vsll vv2, vv2, vs52
    vmul vs3, vs50, vs54
    vsll vs3, vs3, vs52
    vsll vs5, vs54, vs52
    @vp6 vsll vv3, vv5, vs52
.Ldynproc_kernel_skip2:
    vpop vp4, vp6, vp6, vp6, 0xAA
    @vp6 vadd vs6, vs0, vs0
    @vp6 vadd vs7, vs0, vs0
    vpclear vp5
.Ldynproc_kernel_loop3:
    vmul vs8, vs5, vs6
    vadd vs8, vs3, vs8
    vadd vs8, vs48, vs8
    vadd vs9, vs6, vs49
    vaddw vs10, vs7, vs57
    vcmpltu vp6, vs6, vv0
    vpop vp8, vp4, vp6, vp6, 0x80
    vpop vp9, vp4, vp6, vp6, 0x02
    @!vp8 vcjal 0, vs1, .Ldynproc_kernel_skip4
    vsubw vs11, vs2, vs7
    vcmplt vp6, vs11, vv0
    vpop vp6, vp6, vp6, vp6, 0x55
    @vp6 vpop vp6, vp2, vp2, vp2, 0xAA
    @!vp6 vpop vp6, vp1, vp1, vp1, 0xAA
    @vp6 vpop vp6, vp3, vp3, vp3, 0xAA
    @!vp6 vpop vp6, vp1, vp1, vp1, 0xAA
.Ldynproc_kernel_skip4:
    vpop vp10, vp8, vp6, vp6, 0x80
    vpop vp11, vp8, vp6, vp6, 0x02
    @!vp10 vcjal 0, vs1, .Ldynproc_kernel_skip5
    @vp10 vlxw vv6, vs61, vv1
    @vp10 vlw vv7, va0
    @vp10 vlxw vv8, vs61, vv2
    vcmplt vp6, vv6, vv7
    @vp6 vaddw vv6, vv6, vs0
    @!vp6 vaddw vv6, vv7, vs0
    vcmplt vp6, vv6, vv8
    @vp6 vaddw vv6, vv6, vs0
    @!vp6 vaddw vv6, vv8, vs0
    @vp10 vlxw vv7, vs8, vv3
    @vp10 vaddw vv6, vv6, vv7
    @vp10 vsw vv6, va1
.Ldynproc_kernel_skip5:
    vpop vp6, vp10, vp10, vp10, 0xAA
    vpop vp6, vp6, vp11, vp11, 0xEE
    vpop vp6, vp6, vp9, vp9, 0xEE
    @vp10 vpop vp8, vp0, vp0, vp0, 0xAA
    @vp11 vpop vp8, vp1, vp1, vp1, 0xAA
    @vp9 vpop vp8, vp1, vp1, vp1, 0xAA
    @!vp6 vcjal 0, vs1, .Ldynproc_kernel_skip6
    vfence
    vadd vv4, vs6, vs0
    vcmpeq vp9, vv4, vs4
.Ldynproc_kernel_skip6:
    vpop vp10, vp6, vp9, vp9, 0x80
    vpop vp11, vp6, vp9, vp9, 0x02
    @vp10 vpop vp12, vp8, vp8, vp8, 0xAA
    vpop vp5, vp5, vp10, vp10, 0xEE
    vpop vp4, vp4, vp10, vp10, 0x02
    vpop vp6, vp11, vp8, vp8, 0x80
    vpop vp9, vp11, vp8, vp8, 0x02
    @!vp6 vcjal 0, vs1, .Ldynproc_kernel_skip7
    @vp6 vlw vv6, va1
    @vp6 vsw vv6, va0
.Ldynproc_kernel_skip7:
    vpop vp8, vp6, vp6, vp6, 0xAA
    vpop vp8, vp8, vp9, vp9, 0xEE
    vfence
    @vp8 vadd vs6, vs9, vs0
    @vp8 vadd vs7, vs10, vs0
    @vp8 vcjal 1, vs1, .Ldynproc_kernel_loop3
    vpop vp2, vp10, vp10, vp10, 0xAA
    vpop vp2, vp2, vp5, vp5, 0xEE
    vpop vp3, vp2, vp12, vp12, 0x80
    vpop vp4, vp2, vp12, vp12, 0x02
    vpop vp2, vp3, vp3, vp3, 0xAA
    vpop vp2, vp2, vp7, vp7, 0xEE
    @!vp2 vcjal 0, vs1, .Ldynproc_kernel_skip8
    @vp2 vlw vv6, va1
    @vp2 vsll vv1, vv5, vs52
    @vp2 vsxw vv6, vs59, vv1
.Ldynproc_kernel_skip8:
    vpop vp3, vp2, vp2, vp2, 0xAA
    vpop vp3, vp3, vp4, vp4, 0xEE
    vstop

# ---- control threads (from llc) ----
	.file	"hwacha-ct"
	.text
	.globl	dynproc_kernel_ct               # -- Begin function dynproc_kernel_ct
	.p2align	2
	.type	dynproc_kernel_ct,@function
dynproc_kernel_ct:                      # @dynproc_kernel_ct
	.cfi_startproc
# %bb.0:                                # %entry
	ld	a6, 16(sp)
	lui	t0, 1048541
	addi	t0, t0, -1035
	lw	t1, 0(sp)
	srli	t0, t0, 1
	lw	t2, 8(sp)
	not	t0, t0
	#APP
	vsetcfg t0
	#NO_APP
	#APP
	vmcs vs61, a6
	#NO_APP
	#APP
	vmcs vs60, a3
	#NO_APP
	#APP
	vmcs vs59, a4
	#NO_APP
	sext.w	a1, a1
	li	a3, 1
	#APP
	vmcs vs58, a1
	#NO_APP
	#APP
	vmcs vs57, a3
	#NO_APP
	#APP
	vmcs vs56, t2
	#NO_APP
	sext.w	a5, a5
	#APP
	vmcs vs55, t1
	#NO_APP
	#APP
	vmcs vs54, a5
	#NO_APP
	li	a1, -1
	li	a4, 2
	#APP
	vmcs vs53, a1
	#NO_APP
	#APP
	vmcs vs52, a4
	#NO_APP
	li	a1, -2
	sext.w	a7, a7
	#APP
	vmcs vs51, a1
	#NO_APP
	#APP
	vmcs vs50, a7
	#NO_APP
	#APP
	vmcs vs49, a3
	#NO_APP
	li	a1, 32
	#APP
	vmcs vs48, a2
	#NO_APP
	#APP
	vmcs vs47, a1
	#NO_APP
	beqz	a0, .LBB0_7
# %bb.1:                                # %stripmine.preheader
	li	a1, 0
	ld	a2, 24(sp)
.Lpcrel_hi0:
	auipc	a3, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi2:
	auipc	a5, %pcrel_hi(dynproc_kernel_wt)
.Lpcrel_hi1:
	auipc	a4, %pcrel_hi(hwacha_vl_short)
	addi	a5, a5, %pcrel_lo(.Lpcrel_hi2)
	j	.LBB0_3
.LBB0_2:                                # %stripmine
                                        #   in Loop: Header=BB0_3 Depth=1
	#APP
	vsetvl a7, t0
	#NO_APP
	ld	t1, %pcrel_lo(.Lpcrel_hi1)(a4)
	sltu	t0, a7, t0
	or	t0, t1, t0
	sub	a0, a0, a7
	sd	t0, %pcrel_lo(.Lpcrel_hi1)(a4)
	#APP
	vmca va0, a6
	#NO_APP
	#APP
	vmca va1, a2
	#NO_APP
	#APP
	vmcs vs63, a7
	#NO_APP
	#APP
	vmcs vs62, a1
	#NO_APP
	#APP
	vf 0(a5)
	#NO_APP
	addi	a1, a1, 1
	beqz	a0, .LBB0_7
.LBB0_3:                                # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	t0, %pcrel_lo(.Lpcrel_hi0)(a3)
	mv	a7, a0
	beqz	t0, .LBB0_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB0_3 Depth=1
	mv	a7, t0
.LBB0_5:                                # %stripmine
                                        #   in Loop: Header=BB0_3 Depth=1
	mv	t0, a0
	bltu	a0, a7, .LBB0_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB0_3 Depth=1
	mv	t0, a7
	j	.LBB0_2
.LBB0_7:                                # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end0:
	.size	dynproc_kernel_ct, .Lfunc_end0-dynproc_kernel_ct
	.cfi_endproc
                                        # -- End function
	.type	hwacha_group_size,@object       # @hwacha_group_size
	.bss
	.weak	hwacha_group_size
	.p2align	3, 0x0
hwacha_group_size:
	.quad	0                               # 0x0
	.size	hwacha_group_size, 8

	.type	hwacha_vl_short,@object         # @hwacha_vl_short
	.weak	hwacha_vl_short
	.p2align	3, 0x0
hwacha_vl_short:
	.quad	0                               # 0x0
	.size	hwacha_vl_short, 8

	.section	".note.GNU-stack","",@progbits
