# generated by hwacha-cc from bfs_Kernels.ll
# ---- worker threads (vector-fetch blocks) ----

    .text
    .align 3
    .globl BFS_1_wt
BFS_1_wt:
    vpset vp0
    veidx vv0
    vadd vv0, vv0, vs1
    vcmplt vp1, vv0, vs2
    vpop vp2, vp0, vp1, vp1, 0x80
    vpop vp3, vp0, vp1, vp1, 0x02
    @!vp2 vcjal 0, vs8, .LBFS_1_skip0
    @vp2 vlb vv4, va0
    vcmpeq vp1, vv4, vs0
.LBFS_1_skip0:
    vpop vp4, vp2, vp1, vp1, 0x80
    vpop vp5, vp2, vp1, vp1, 0x02
    @!vp5 vcjal 0, vs8, .LBFS_1_skip1
    vaddw vv4, vs0, vs0
    @vp5 vsb vv4, va0
    @vp5 vlw vv4, va1
    vcmplt vp1, vs0, vv4
.LBFS_1_skip1:
    vpop vp2, vp5, vp1, vp1, 0x80
    vpop vp6, vp5, vp1, vp1, 0x02
    @!vp2 vcjal 0, vs8, .LBFS_1_skip2
    @vp2 vlw vv5, va2
    @vp2 vsll vv1, vv5, vs3
.LBFS_1_skip2:
    vpop vp1, vp2, vp2, vp2, 0xAA
    @vp2 vadd vs9, vs0, vs0
    @vp2 vaddw vv6, vv5, vs0
    @vp2 vaddw vv7, vv4, vs0
    @vp2 vadd vv2, vv5, vs0
    vpclear vp5
.LBFS_1_loop3:
    vsll vs10, vs9, vs3
    vadd vs10, vs4, vs10
    @vp1 vlxw vv8, vs10, vv1
    @vp1 vlxb vv9, vs10, vv8
    vcmpeq vp2, vv9, vs0
    vpop vp7, vp1, vp2, vp2, 0x80
    vpop vp8, vp1, vp2, vp2, 0x02
    @!vp7 vcjal 0, vs8, .LBFS_1_skip4
    @vp7 vlw vv9, va3
    @vp7 vaddw vv9, vv9, vs5
    @vp7 vsll vv3, vv8, vs3
    @vp7 vsxw vv9, vs11, vv3
    @vp7 vsxb vs6, vs12, vv8
    @vp7 vlw vv8, va1
    @vp7 vlw vv9, va2
.LBFS_1_skip4:
    vpop vp2, vp7, vp7, vp7, 0xAA
    vpop vp2, vp2, vp8, vp8, 0xEE
    @vp7 vaddw vv10, vv9, vs0
    @vp8 vaddw vv10, vv6, vs0
    @vp7 vaddw vv11, vv8, vs0
    @vp8 vaddw vv11, vv7, vs0
    @!vp2 vcjal 0, vs8, .LBFS_1_skip5
    @vp2 vadd vv3, vv2, vs7
    @vp2 vaddw vv8, vv10, vv11
    vcmplt vp7, vv3, vv8
    vadd vs13, vs9, vs7
.LBFS_1_skip5:
    vpop vp8, vp2, vp7, vp7, 0x80
    vpop vp9, vp2, vp7, vp7, 0x02
    vpop vp5, vp5, vp9, vp9, 0xEE
    vpop vp1, vp1, vp9, vp9, 0x02
    @vp8 vadd vs9, vs13, vs0
    @vp8 vaddw vv6, vv10, vs0
    @vp8 vaddw vv7, vv11, vs0
    @vp8 vadd vv2, vv3, vs0
    @vp8 vcjal 1, vs8, .LBFS_1_loop3
    vpop vp1, vp9, vp9, vp9, 0xAA
    vpop vp1, vp1, vp5, vp5, 0xEE
    vpop vp2, vp1, vp1, vp1, 0xAA
    vpop vp2, vp2, vp6, vp6, 0xEE
    vpop vp2, vp2, vp4, vp4, 0xEE
    vpop vp2, vp2, vp3, vp3, 0xEE
    vstop

    .text
    .align 3
    .globl BFS_2_wt
BFS_2_wt:
    vpset vp0
    veidx vv0
    vadd vv0, vv0, vs1
    vcmplt vp1, vv0, vs2
    vpop vp2, vp0, vp1, vp1, 0x80
    vpop vp3, vp0, vp1, vp1, 0x02
    @!vp2 vcjal 0, vs5, .LBFS_2_skip0
    @vp2 vlb vv1, va0
    vcmpeq vp1, vv1, vs0
.LBFS_2_skip0:
    vpop vp4, vp2, vp1, vp1, 0x80
    vpop vp5, vp2, vp1, vp1, 0x02
    @!vp5 vcjal 0, vs5, .LBFS_2_skip1
    vaddw vv1, vs3, vs0
    @vp5 vsb vv1, va1
    vaddw vv1, vs3, vs0
    @vp5 vsb vv1, va2
    vssb vs4, vs3
    vaddw vv1, vs0, vs0
    @vp5 vsb vv1, va0
.LBFS_2_skip1:
    vpop vp1, vp5, vp5, vp5, 0xAA
    vpop vp1, vp1, vp4, vp4, 0xEE
    vpop vp1, vp1, vp3, vp3, 0xEE
    vstop

# ---- control threads (from llc) ----
	.file	"hwacha-ct"
	.text
	.globl	BFS_1_ct                        # -- Begin function BFS_1_ct
	.p2align	2
	.type	BFS_1_ct,@function
BFS_1_ct:                               # @BFS_1_ct
	.cfi_startproc
# %bb.0:                                # %entry
	lui	t0, 1048509
	addi	t0, t0, 2039
	srli	t0, t0, 1
	not	t0, t0
	#APP
	vsetcfg t0
	#NO_APP
	sext.w	a7, a7
	li	t0, 2
	#APP
	vmcs vs2, a7
	#NO_APP
	#APP
	vmcs vs3, t0
	#NO_APP
	#APP
	vmcs vs4, a2
	#NO_APP
	li	a2, 1
	#APP
	vmcs vs5, a2
	#NO_APP
	#APP
	vmcs vs6, a2
	#NO_APP
	#APP
	vmcs vs7, a2
	#NO_APP
	#APP
	vmcs vs10, a5
	#NO_APP
	#APP
	vmcs vs11, a6
	#NO_APP
	#APP
	vmcs vs12, a4
	#NO_APP
	beqz	a0, .LBB0_3
# %bb.1:                                # %stripmine.preheader
	li	a2, 0
.Lpcrel_hi0:
	auipc	a5, %pcrel_hi(BFS_1_wt)
	addi	a4, a1, 4
	addi	a5, a5, %pcrel_lo(.Lpcrel_hi0)
.LBB0_2:                                # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	#APP
	vsetvl a7, a0
	#NO_APP
	#APP
	vmca va0, a3
	#NO_APP
	#APP
	vmca va1, a4
	#NO_APP
	#APP
	vmca va2, a1
	#NO_APP
	#APP
	vmca va3, a6
	#NO_APP
	#APP
	vmcs vs1, a2
	#NO_APP
	#APP
	vf 0(a5)
	#NO_APP
	sub	a0, a0, a7
	add	a2, a2, a7
	add	a3, a3, a7
	slli	t0, a7, 3
	add	a4, a4, t0
	slli	a7, a7, 2
	add	a1, a1, t0
	add	a6, a6, a7
	bnez	a0, .LBB0_2
.LBB0_3:                                # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end0:
	.size	BFS_1_ct, .Lfunc_end0-BFS_1_ct
	.cfi_endproc
                                        # -- End function
	.globl	BFS_2_ct                        # -- Begin function BFS_2_ct
	.p2align	2
	.type	BFS_2_ct,@function
BFS_2_ct:                               # @BFS_2_ct
	.cfi_startproc
# %bb.0:                                # %entry
	lui	a6, 1048566
	addi	a6, a6, 2045
	srli	a6, a6, 1
	not	a6, a6
	#APP
	vsetcfg a6
	#NO_APP
	sext.w	a5, a5
	#APP
	vmcs vs2, a5
	#NO_APP
	li	a5, 1
	#APP
	vmcs vs3, a5
	#NO_APP
	#APP
	vmcs vs4, a4
	#NO_APP
	beqz	a0, .LBB1_3
# %bb.1:                                # %stripmine.preheader
	li	a4, 0
.Lpcrel_hi1:
	auipc	a5, %pcrel_hi(BFS_2_wt)
	addi	a5, a5, %pcrel_lo(.Lpcrel_hi1)
.LBB1_2:                                # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	#APP
	vsetvl a6, a0
	#NO_APP
	#APP
	vmca va0, a2
	#NO_APP
	#APP
	vmca va1, a1
	#NO_APP
	#APP
	vmca va2, a3
	#NO_APP
	#APP
	vmcs vs1, a4
	#NO_APP
	#APP
	vf 0(a5)
	#NO_APP
	sub	a0, a0, a6
	add	a4, a4, a6
	add	a2, a2, a6
	add	a1, a1, a6
	add	a3, a3, a6
	bnez	a0, .LBB1_2
.LBB1_3:                                # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end1:
	.size	BFS_2_ct, .Lfunc_end1-BFS_2_ct
	.cfi_endproc
                                        # -- End function
	.section	".note.GNU-stack","",@progbits
