# generated by hwacha-cc from kmeans_kmeans.ll
# ---- worker threads (vector-fetch blocks) ----

    .text
    .align 3
    .globl kmeans_kernel_c_wt
kmeans_kernel_c_wt:
    vpset vp0
    veidx vv0
    vadd vv0, vv0, vs1
    vcmpltu vp1, vv0, vs2
    vpop vp2, vp0, vp1, vp1, 0x80
    vpop vp3, vp0, vp1, vp1, 0x02
    @!vp2 vcjal 0, vs9, .Lkmeans_kernel_c_skip0
    vaddw vv3, vs0, vs0
    vcmplt vp1, vv3, vs3
.Lkmeans_kernel_c_skip0:
    vpop vp4, vp2, vp1, vp1, 0x80
    vpop vp5, vp2, vp1, vp1, 0x02
    @!vp4 vcjal 0, vs9, .Lkmeans_kernel_c_skip1
    vaddw vv3, vs0, vs0
    vcmplt vp1, vv3, vs4
    vsll vs10, vs4, vs11
    vsrl vs10, vs10, vs11
    vsll vs12, vs3, vs11
    vsrl vs12, vs12, vs11
    vsll vs13, vs2, vs11
    vsrl vs13, vs13, vs11
.Lkmeans_kernel_c_skip1:
    vpop vp2, vp4, vp4, vp4, 0xAA
    @vp4 vadd vs14, vs0, vs0
    @vp4 vaddw vv3, vs5, vs0
    @vp4 vaddw vv4, vs0, vs0
    vpclear vp6
.Lkmeans_kernel_c_loop2:
    vpop vp4, vp2, vp1, vp1, 0x80
    vpop vp7, vp2, vp1, vp1, 0x02
    @!vp4 vcjal 0, vs9, .Lkmeans_kernel_c_skip3
    vmul vs15, vs14, vs10
    vmul vs16, vs15, vs17
    vadd vs15, vs6, vs16
.Lkmeans_kernel_c_skip3:
    vpop vp8, vp4, vp4, vp4, 0xAA
    @vp4 vadd vs16, vs0, vs0
    @vp4 vaddw vv5, vs0, vs0
    vpclear vp9
.Lkmeans_kernel_c_loop4:
    vmul vs18, vs13, vs16
    @vp8 vadd vv1, vv0, vs18
    vsll vv2, vv1, vs11
    vsrl vv2, vv2, vs11
    @vp8 vsll vv2, vv2, vs8
    @vp8 vlxw vv6, vs18, vv2
    vmul vs20, vs16, vs17
    vadd vs19, vs15, vs20
    vlsw vs19, vs19
    @vp8 vfsub.s vv6, vv6, vs19
    @vp8 vfmadd.s vv6, vv6, vv6, vv5
    vadd vs19, vs16, vs7
    vadd vv1, vs19, vs0
    vcmpeq vp4, vv1, vs10
    vpop vp10, vp8, vp4, vp4, 0x80
    vpop vp11, vp8, vp4, vp4, 0x02
    @vp10 vaddw vv7, vv6, vs0
    vpop vp9, vp9, vp10, vp10, 0xEE
    vpop vp8, vp8, vp10, vp10, 0x02
    @vp11 vadd vs16, vs19, vs0
    @vp11 vaddw vv5, vv6, vs0
    @vp11 vcjal 1, vs9, .Lkmeans_kernel_c_loop4
    vpop vp4, vp9, vp9, vp9, 0xAA
    vpop vp4, vp4, vp7, vp7, 0xEE
    @vp7 vaddw vv5, vs0, vs0
    @vp9 vaddw vv5, vv7, vs0
    @!vp4 vcjal 0, vs9, .Lkmeans_kernel_c_skip5
    vcmpflt.s vp7, vv5, vv3
    @vp7 vaddw vv6, vs14, vs0
    @!vp7 vaddw vv6, vv4, vs0
    @!vp7 vaddw vv5, vv3, vs0
    vadd vs15, vs14, vs7
    vadd vv1, vs15, vs0
    vcmpeq vp7, vv1, vs12
.Lkmeans_kernel_c_skip5:
    vpop vp8, vp4, vp7, vp7, 0x80
    vpop vp9, vp4, vp7, vp7, 0x02
    @vp8 vaddw vv7, vv6, vs0
    vpop vp6, vp6, vp8, vp8, 0xEE
    vpop vp2, vp2, vp8, vp8, 0x02
    @vp9 vadd vs14, vs15, vs0
    @vp9 vaddw vv3, vv5, vs0
    @vp9 vaddw vv4, vv6, vs0
    @vp9 vcjal 1, vs9, .Lkmeans_kernel_c_loop2
    vpop vp1, vp8, vp8, vp8, 0xAA
    vpop vp1, vp1, vp6, vp6, 0xEE
    vpop vp2, vp1, vp1, vp1, 0xAA
    vpop vp2, vp2, vp5, vp5, 0xEE
    @vp5 vaddw vv3, vs0, vs0
    @vp1 vaddw vv3, vv7, vs0
    @vp2 vsw vv3, va0
    vpop vp1, vp2, vp2, vp2, 0xAA
    vpop vp1, vp1, vp3, vp3, 0xEE
    vstop

    .text
    .align 3
    .globl kmeans_swap_wt
kmeans_swap_wt:
    vpset vp0
    veidx vv0
    vadd vv0, vv0, vs1
    vcmpltu vp1, vv0, vs2
    vaddw vv5, vs0, vs0
    vcmplt vp2, vv5, vs3
    vpop vp1, vp1, vp2, vp1, 136
    vpop vp2, vp0, vp1, vp1, 0x80
    vpop vp3, vp0, vp1, vp1, 0x02
    @!vp2 vcjal 0, vs9, .Lkmeans_swap_skip0
    @vp2 vmulw vv5, vs3, vv0
    vsll vs6, vs3, vs7
    vsrl vs6, vs6, vs7
    vsll vv1, vv5, vs7
    vsrl vv1, vv1, vs7
    vsll vs8, vs2, vs7
    vsrl vs8, vs8, vs7
.Lkmeans_swap_skip0:
    vpop vp1, vp2, vp2, vp2, 0xAA
    @vp2 vadd vs10, vs0, vs0
    vpclear vp4
.Lkmeans_swap_loop1:
    @vp1 vadd vv2, vv1, vs10
    vsll vv3, vv2, vs7
    vsrl vv3, vv3, vs7
    @vp1 vsll vv3, vv3, vs4
    vmul vs11, vs8, vs10
    @vp1 vadd vv2, vv0, vs11
    vsll vv4, vv2, vs7
    vsrl vv4, vv4, vs7
    @vp1 vsll vv4, vv4, vs4
    @vp1 vlxw vv6, vs11, vv3
    @vp1 vsxw vv6, vs12, vv4
    vadd vs13, vs10, vs5
    vadd vv2, vs13, vs0
    vcmpeq vp2, vv2, vs6
    vpop vp5, vp1, vp2, vp2, 0x80
    vpop vp6, vp1, vp2, vp2, 0x02
    vpop vp4, vp4, vp5, vp5, 0xEE
    vpop vp1, vp1, vp5, vp5, 0x02
    @vp6 vadd vs10, vs13, vs0
    @vp6 vcjal 1, vs9, .Lkmeans_swap_loop1
    vpop vp1, vp4, vp4, vp4, 0xAA
    vpop vp1, vp1, vp3, vp3, 0xEE
    vstop

# ---- control threads (from llc) ----
	.file	"hwacha-ct"
	.text
	.globl	kmeans_kernel_c_ct              # -- Begin function kmeans_kernel_c_ct
	.p2align	2
	.type	kmeans_kernel_c_ct,@function
kmeans_kernel_c_ct:                     # @kmeans_kernel_c_ct
	.cfi_startproc
# %bb.0:                                # %entry
	lui	a7, 1048533
	addi	a7, a7, -7
	srli	a7, a7, 1
	not	a7, a7
	#APP
	vsetcfg a7
	#NO_APP
	sext.w	a4, a4
	#APP
	vmcs vs2, a4
	#NO_APP
	sext.w	a5, a5
	#APP
	vmcs vs3, a5
	#NO_APP
	lui	a4, 522240
	sext.w	a6, a6
	addi	a4, a4, -1
	#APP
	vmcs vs4, a6
	#NO_APP
	#APP
	vmcs vs5, a4
	#NO_APP
	#APP
	vmcs vs6, a2
	#NO_APP
	li	a2, 1
	#APP
	vmcs vs7, a2
	#NO_APP
	li	a2, 2
	#APP
	vmcs vs8, a2
	#NO_APP
	li	a2, 32
	#APP
	vmcs vs11, a2
	#NO_APP
	li	a2, 4
	#APP
	vmcs vs17, a2
	#NO_APP
	#APP
	vmcs vs18, a1
	#NO_APP
	beqz	a0, .LBB0_3
# %bb.1:                                # %stripmine.preheader
	li	a1, 0
.Lpcrel_hi0:
	auipc	a2, %pcrel_hi(kmeans_kernel_c_wt)
	addi	a2, a2, %pcrel_lo(.Lpcrel_hi0)
.LBB0_2:                                # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	#APP
	vsetvl a4, a0
	#NO_APP
	#APP
	vmca va0, a3
	#NO_APP
	#APP
	vmcs vs1, a1
	#NO_APP
	sub	a0, a0, a4
	add	a1, a1, a4
	slli	a4, a4, 2
	#APP
	vf 0(a2)
	#NO_APP
	add	a3, a3, a4
	bnez	a0, .LBB0_2
.LBB0_3:                                # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end0:
	.size	kmeans_kernel_c_ct, .Lfunc_end0-kmeans_kernel_c_ct
	.cfi_endproc
                                        # -- End function
	.globl	kmeans_swap_ct                  # -- Begin function kmeans_swap_ct
	.p2align	2
	.type	kmeans_swap_ct,@function
kmeans_swap_ct:                         # @kmeans_swap_ct
	.cfi_startproc
# %bb.0:                                # %entry
	lui	a5, 1048558
	addi	a5, a5, 1013
	srli	a5, a5, 1
	not	a5, a5
	sext.w	a3, a3
	#APP
	vsetcfg a5
	#NO_APP
	#APP
	vmcs vs2, a3
	#NO_APP
	sext.w	a4, a4
	li	a3, 2
	#APP
	vmcs vs3, a4
	#NO_APP
	#APP
	vmcs vs4, a3
	#NO_APP
	li	a3, 1
	li	a4, 32
	#APP
	vmcs vs5, a3
	#NO_APP
	#APP
	vmcs vs7, a4
	#NO_APP
	#APP
	vmcs vs11, a1
	#NO_APP
	#APP
	vmcs vs12, a2
	#NO_APP
	beqz	a0, .LBB1_3
# %bb.1:                                # %stripmine.preheader
	li	a1, 0
.Lpcrel_hi1:
	auipc	a2, %pcrel_hi(kmeans_swap_wt)
	addi	a2, a2, %pcrel_lo(.Lpcrel_hi1)
.LBB1_2:                                # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	#APP
	vsetvl a3, a0
	#NO_APP
	#APP
	vmcs vs1, a1
	#NO_APP
	sub	a0, a0, a3
	#APP
	vf 0(a2)
	#NO_APP
	add	a1, a1, a3
	bnez	a0, .LBB1_2
.LBB1_3:                                # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end1:
	.size	kmeans_swap_ct, .Lfunc_end1-kmeans_swap_ct
	.cfi_endproc
                                        # -- End function
	.section	".note.GNU-stack","",@progbits
