# generated by hwacha-cc from nn_nearestNeighbor_kernel.ll
# ---- worker threads (vector-fetch blocks) ----

    .text
    .align 3
    .globl NearestNeighbor_wt
NearestNeighbor_wt:
    vpset vp0
    veidx vv0
    vadd vv0, vv0, vs1
    vcmplt vp1, vv0, vs2
    vpop vp2, vp0, vp1, vp1, 0x80
    vpop vp3, vp0, vp1, vp1, 0x02
    @!vp2 vcjal 0, vs5, .LNearestNeighbor_skip0
    @vp2 vlw vv1, va0
    @vp2 vfsub.s vv2, vs3, vv1
    @vp2 vlw vv1, va1
    @vp2 vfsub.s vv3, vs4, vv1
    @vp2 vfmul.s vv3, vv3, vv3
    @vp2 vfmadd.s vv2, vv2, vv2, vv3
    @vp2 vfsqrt.s vv2, vv2
    @vp2 vsw vv2, va2
.LNearestNeighbor_skip0:
    vpop vp1, vp2, vp2, vp2, 0xAA
    vpop vp1, vp1, vp3, vp3, 0xEE
    vstop

# ---- control threads (from llc) ----
	.file	"hwacha-ct"
	.text
	.globl	NearestNeighbor_ct              # -- Begin function NearestNeighbor_ct
	.p2align	2
	.type	NearestNeighbor_ct,@function
NearestNeighbor_ct:                     # @NearestNeighbor_ct
	.cfi_startproc
# %bb.0:                                # %entry
	fmv.x.s	a4, fa0
	fmv.x.s	a5, fa1
	lui	a6, 1048551
	addi	a6, a6, -3
	srli	a6, a6, 1
	not	a6, a6
	sext.w	a3, a3
	#APP
	vsetcfg a6
	#NO_APP
	#APP
	vmcs vs2, a3
	#NO_APP
	slli	a4, a4, 32
	slli	a5, a5, 32
	srli	a4, a4, 32
	srli	a5, a5, 32
	#APP
	vmcs vs3, a4
	#NO_APP
	#APP
	vmcs vs4, a5
	#NO_APP
	beqz	a0, .LBB0_3
# %bb.1:                                # %stripmine.preheader
	li	a3, 0
.Lpcrel_hi0:
	auipc	a5, %pcrel_hi(NearestNeighbor_wt)
	addi	a4, a1, 4
	addi	a5, a5, %pcrel_lo(.Lpcrel_hi0)
.LBB0_2:                                # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	#APP
	vsetvl a6, a0
	#NO_APP
	#APP
	vmca va0, a1
	#NO_APP
	#APP
	vmca va1, a4
	#NO_APP
	#APP
	vmca va2, a2
	#NO_APP
	#APP
	vmcs vs1, a3
	#NO_APP
	#APP
	vf 0(a5)
	#NO_APP
	sub	a0, a0, a6
	add	a3, a3, a6
	slli	a7, a6, 3
	add	a1, a1, a7
	slli	a6, a6, 2
	add	a4, a4, a7
	add	a2, a2, a6
	bnez	a0, .LBB0_2
.LBB0_3:                                # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end0:
	.size	NearestNeighbor_ct, .Lfunc_end0-NearestNeighbor_ct
	.cfi_endproc
                                        # -- End function
	.section	".note.GNU-stack","",@progbits
