# generated by hwacha-cc from pathfinder_kernels.ll
# ---- worker threads (vector-fetch blocks) ----

    .text
    .align 3
    .globl dynproc_kernel_wt
dynproc_kernel_wt:
    vpset vp0
    veidx vv0
    vsllw vs15, vs3, vs4
    vmulw vs15, vs15, vs5
    vsubw vs15, vs1, vs15
    vmulw vs15, vs15, vs2
    vsubw vs15, vs15, vs6
    vaddw vs16, vs15, vs1
    vaddw vv5, vs15, vv0
    vaddw vv6, vs15, vs0
    vcmplt vp1, vv6, vs0
    @vp1 vaddw vs15, vv6, vs0
    @!vp1 vaddw vs15, vs0, vs0
    vsubw vs15, vs0, vs15
    vaddw vv6, vs7, vs0
    vcmplt vp1, vv6, vs16
    vaddw vs17, vs1, vs8
    @vp1 vsubw vs18, vs7, vs16
    @!vp1 vaddw vs18, vs0, vs0
    vaddw vs17, vs17, vs18
    vaddw vv6, vv0, vs8
    vcmplt vp1, vv6, vs15
    @vp1 vaddw vv6, vs15, vs0
    @!vp1 vaddw vv6, vv6, vs0
    vcmplt vp1, vv0, vs15
    vpop vp1, vp1, vp1, vp1, 0x55
    vcmplt vp2, vs17, vv0
    vpop vp2, vp2, vp2, vp2, 0x55
    vcmplt vp3, vs8, vv5
    vcmplt vp4, vv5, vs7
    vpop vp3, vp3, vp4, vp3, 136
    vpop vp4, vp0, vp3, vp3, 0x80
    vpop vp5, vp0, vp3, vp3, 0x02
    @!vp4 vcjal 0, vs18, .Ldynproc_kernel_skip0
    vsll vv1, vv5, vs15
    vsrl vv1, vv1, vs15
    @vp4 vsll vv1, vv1, vs9
    @vp4 vlxw vv7, vs16, vv1
    @vp4 vsw vv7, va0
.Ldynproc_kernel_skip0:
    vpop vp3, vp4, vp4, vp4, 0xAA
    vpop vp3, vp3, vp5, vp5, 0xEE
    @!vp3 vcjal 0, vs18, .Ldynproc_kernel_skip1
    vfence
    vaddw vv7, vs0, vs0
    vcmplt vp4, vv7, vs3
.Ldynproc_kernel_skip1:
    vpop vp5, vp3, vp4, vp4, 0x80
    vpop vp6, vp3, vp4, vp4, 0x02
    @!vp5 vcjal 0, vs18, .Ldynproc_kernel_skip2
    vaddw vs19, vs1, vs10
    vsll vv1, vv6, vs15
    vsrl vv1, vv1, vs15
    vcmpeq vp3, vv0, vs11
    vaddw vs20, vs3, vs8
    vsll vs20, vs20, vs15
    vsrl vs20, vs20, vs15
    @vp5 vsll vv1, vv1, vs9
    @vp5 vadd vv2, vv0, vs13
    vcmplt vp4, vv2, vs17
    @vp4 vadd vv2, vv2, vs0
    @!vp4 vadd vv2, vs17, vs0
    @vp5 vsll vv2, vv2, vs9
    vmul vs17, vs12, vs7
    vsll vs17, vs17, vs9
    vsll vs21, vs7, vs9
    @vp5 vsll vv3, vv5, vs9
.Ldynproc_kernel_skip2:
    vpop vp4, vp5, vp5, vp5, 0xAA
    @vp5 vadd vs22, vs0, vs0
    @vp5 vadd vs23, vs0, vs0
    vpclear vp7
.Ldynproc_kernel_loop3:
    vmul vs24, vs21, vs22
    vadd vs24, vs17, vs24
    vadd vs24, vs14, vs24
    vadd vs25, vs22, vs13
    vaddw vs26, vs23, vs4
    vcmpltu vp5, vs22, vv0
    vpop vp8, vp4, vp5, vp5, 0x80
    vpop vp9, vp4, vp5, vp5, 0x02
    @!vp8 vcjal 0, vs18, .Ldynproc_kernel_skip4
    vsubw vs27, vs19, vs23
    vcmplt vp5, vs27, vv0
    vpop vp5, vp5, vp5, vp5, 0x55
    @vp5 vaddw vp5, vp1, vs0
    @!vp5 vaddw vp5, vs0, vs0
    @vp5 vaddw vp5, vp2, vs0
    @!vp5 vaddw vp5, vs0, vs0
.Ldynproc_kernel_skip4:
    vpop vp10, vp8, vp5, vp5, 0x80
    vpop vp11, vp8, vp5, vp5, 0x02
    @!vp10 vcjal 0, vs18, .Ldynproc_kernel_skip5
    @vp10 vlxw vv6, vs27, vv1
    @vp10 vlw vv7, va0
    @vp10 vlxw vv8, vs27, vv2
    vcmplt vp5, vv6, vv7
    @vp5 vaddw vv6, vv6, vs0
    @!vp5 vaddw vv6, vv7, vs0
    vcmplt vp5, vv6, vv8
    @vp5 vaddw vv6, vv6, vs0
    @!vp5 vaddw vv6, vv8, vs0
    @vp10 vlxw vv7, vs24, vv3
    @vp10 vaddw vv6, vv6, vv7
    @vp10 vsw vv6, va1
    vadd vv4, vs22, vs0
    vcmpeq vp5, vv4, vs0
    vpop vp5, vp3, vp5, vp3, 136
.Ldynproc_kernel_skip5:
    vpop vp8, vp10, vp5, vp5, 0x80
    vpop vp12, vp10, vp5, vp5, 0x02
    @!vp8 vcjal 0, vs18, .Ldynproc_kernel_skip6
    @vp8 vlxw vv6, vs16, vv3
    @vp8 vsll vv4, vv6, vs9
    @vp8 vsxw vs4, vs24, vv4
.Ldynproc_kernel_skip6:
    vpop vp5, vp8, vp8, vp8, 0xAA
    vpop vp5, vp5, vp12, vp12, 0xEE
    vpop vp5, vp5, vp11, vp11, 0xEE
    vpop vp5, vp5, vp9, vp9, 0xEE
    @vp9 vpop vp10, vs0, vs0, vs0, 0xAA
    @vp11 vpop vp10, vs0, vs0, vs0, 0xAA
    @vp8 vpop vp10, vs28, vs28, vs28, 0xAA
    @vp12 vpop vp10, vs28, vs28, vs28, 0xAA
    @!vp5 vcjal 0, vs18, .Ldynproc_kernel_skip7
    vfence
    vadd vv4, vs22, vs0
    vcmpeq vp8, vv4, vs20
.Ldynproc_kernel_skip7:
    vpop vp9, vp5, vp8, vp8, 0x80
    vpop vp11, vp5, vp8, vp8, 0x02
    @vp9 vpop vp12, vp10, vp10, vp10, 0xAA
    vpop vp7, vp7, vp9, vp9, 0xEE
    vpop vp4, vp4, vp9, vp9, 0x02
    vpop vp5, vp11, vp10, vp10, 0x80
    vpop vp8, vp11, vp10, vp10, 0x02
    @!vp5 vcjal 0, vs18, .Ldynproc_kernel_skip8
    @vp5 vlw vv6, va1
    @vp5 vsw vv6, va0
.Ldynproc_kernel_skip8:
    vpop vp10, vp5, vp5, vp5, 0xAA
    vpop vp10, vp10, vp8, vp8, 0xEE
    vfence
    @vp10 vadd vs22, vs25, vs0
    @vp10 vadd vs23, vs26, vs0
    @vp10 vcjal 1, vs18, .Ldynproc_kernel_loop3
    vpop vp1, vp9, vp9, vp9, 0xAA
    vpop vp1, vp1, vp7, vp7, 0xEE
    vpop vp2, vp1, vp12, vp12, 0x80
    vpop vp3, vp1, vp12, vp12, 0x02
    vpop vp1, vp2, vp2, vp2, 0xAA
    vpop vp1, vp1, vp6, vp6, 0xEE
    @!vp1 vcjal 0, vs18, .Ldynproc_kernel_skip9
    @vp1 vlw vv6, va1
    @vp1 vsll vv1, vv5, vs9
    @vp1 vsxw vv6, vs17, vv1
.Ldynproc_kernel_skip9:
    vpop vp2, vp1, vp1, vp1, 0xAA
    vpop vp2, vp2, vp3, vp3, 0xEE
    vstop

# ---- control threads (from llc) ----
	.file	"hwacha-ct"
	.text
	.globl	dynproc_kernel_ct               # -- Begin function dynproc_kernel_ct
	.p2align	2
	.type	dynproc_kernel_ct,@function
dynproc_kernel_ct:                      # @dynproc_kernel_ct
	.cfi_startproc
# %bb.0:                                # %entry
	ld	a6, 16(sp)
	lui	t0, 1048541
	ld	t1, 32(sp)
	addi	t0, t0, -1035
	lw	t2, 8(sp)
	srli	t0, t0, 1
	lw	t3, 0(sp)
	not	t0, t0
	#APP
	vsetcfg t0
	#NO_APP
	sext.w	a1, a1
	#APP
	vmcs vs3, a1
	#NO_APP
	li	a1, 1
	#APP
	vmcs vs4, a1
	#NO_APP
	#APP
	vmcs vs5, t2
	#NO_APP
	#APP
	vmcs vs6, t3
	#NO_APP
	sext.w	a5, a5
	#APP
	vmcs vs7, a5
	#NO_APP
	li	a5, -1
	#APP
	vmcs vs8, a5
	#NO_APP
	li	t0, 2
	#APP
	vmcs vs9, t0
	#NO_APP
	li	t0, -2
	#APP
	vmcs vs10, t0
	#NO_APP
	li	t0, 11
	#APP
	vmcs vs11, t0
	#NO_APP
	sext.w	a7, a7
	#APP
	vmcs vs12, a7
	#NO_APP
	#APP
	vmcs vs13, a1
	#NO_APP
	#APP
	vmcs vs14, a2
	#NO_APP
	li	a1, 32
	#APP
	vmcs vs15, a1
	#NO_APP
	#APP
	vmcs vs16, a3
	#NO_APP
	#APP
	vmcs vs27, a6
	#NO_APP
	#APP
	vmcs vs24, t1
	#NO_APP
	#APP
	vmcs vs28, a5
	#NO_APP
	#APP
	vmcs vs17, a4
	#NO_APP
	beqz	a0, .LBB0_3
# %bb.1:                                # %stripmine.preheader
	li	a1, 0
	ld	a2, 24(sp)
.Lpcrel_hi0:
	auipc	a3, %pcrel_hi(dynproc_kernel_wt)
	addi	a3, a3, %pcrel_lo(.Lpcrel_hi0)
.LBB0_2:                                # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	#APP
	vsetvl a4, a0
	#NO_APP
	#APP
	vmca va0, a6
	#NO_APP
	#APP
	vmca va1, a2
	#NO_APP
	#APP
	vmcs vs1, a4
	#NO_APP
	#APP
	vmcs vs2, a1
	#NO_APP
	sub	a0, a0, a4
	#APP
	vf 0(a3)
	#NO_APP
	addi	a1, a1, 1
	bnez	a0, .LBB0_2
.LBB0_3:                                # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end0:
	.size	dynproc_kernel_ct, .Lfunc_end0-dynproc_kernel_ct
	.cfi_endproc
                                        # -- End function
	.section	".note.GNU-stack","",@progbits
