# generated by hwacha-cc from streamcluster_Kernels.ll
# ---- worker threads (vector-fetch blocks) ----

    .text
    .align 3
    .globl memset_kernel_wt
memset_kernel_wt:
    vpset vp0
    vaddw vv0, vs1, vs0
    vsb vv0, va0
    vstop

    .text
    .align 3
    .globl pgain_kernel_wt
pgain_kernel_wt:
    vpset vp0
    veidx vv0
    vadd vv0, vv0, vs1
    veidx vv1
    vcmplt vp1, vv0, vs2
    vpop vp2, vp0, vp1, vp1, 0x80
    vpop vp3, vp0, vp1, vp1, 0x02
    @!vp2 vcjal 0, vs14, .Lpgain_kernel_skip0
    vcmpeq vp1, vv1, vs0
    vaddw vv4, vs0, vs0
    vcmplt vp4, vv4, vs3
    vpop vp1, vp1, vp4, vp1, 136
.Lpgain_kernel_skip0:
    vpop vp5, vp2, vp1, vp1, 0x80
    vpop vp6, vp2, vp1, vp1, 0x02
    @!vp5 vcjal 0, vs14, .Lpgain_kernel_skip1
    vmul vs16, vs5, vs17
    vadd vs15, vs4, vs16
    vsll vs16, vs3, vs12
    vsrl vs16, vs16, vs12
.Lpgain_kernel_skip1:
    vpop vp1, vp5, vp5, vp5, 0xAA
    @vp5 vadd vs18, vs0, vs0
    vpclear vp2
.Lpgain_kernel_loop2:
    vmul vs19, vs18, vs2
    vmul vs20, vs19, vs17
    vadd vs19, vs15, vs20
    vlsw vs19, vs19
    vmul vs21, vs18, vs17
    vadd vs20, vs6, vs21
    vssw vs20, vs19
    vadd vs19, vs18, vs7
    vadd vv2, vs19, vs0
    vcmpeq vp5, vv2, vs16
    vpop vp7, vp1, vp5, vp5, 0x80
    vpop vp8, vp1, vp5, vp5, 0x02
    vpop vp2, vp2, vp7, vp7, 0xEE
    vpop vp1, vp1, vp7, vp7, 0x02
    @vp8 vadd vs18, vs19, vs0
    @vp8 vcjal 1, vs14, .Lpgain_kernel_loop2
    vpop vp1, vp2, vp2, vp2, 0xAA
    vpop vp1, vp1, vp6, vp6, 0xEE
    vfence
    vpop vp2, vp1, vp4, vp4, 0x80
    vpop vp5, vp1, vp4, vp4, 0x02
    @!vp2 vcjal 0, vs14, .Lpgain_kernel_skip3
    @vp2 vsll vv2, vv0, vs9
    vsll vs15, vs3, vs12
    vsrl vs15, vs15, vs12
    vsll vs16, vs2, vs9
.Lpgain_kernel_skip3:
    vpop vp1, vp2, vp2, vp2, 0xAA
    @vp2 vadd vs18, vs0, vs0
    @vp2 vaddw vv4, vs0, vs0
    vpclear vp4
.Lpgain_kernel_loop4:
    vmul vs19, vs16, vs18
    vadd vs19, vs4, vs19
    @vp1 vlxw vv5, vs19, vv2
    vmul vs20, vs18, vs17
    vadd vs19, vs6, vs20
    vlsw vs19, vs19
    @vp1 vfsub.s vv5, vv5, vs19
    @vp1 vfmadd.s vv5, vv5, vv5, vv4
    vadd vs19, vs18, vs7
    vadd vv3, vs19, vs0
    vcmpeq vp2, vv3, vs15
    vpop vp6, vp1, vp2, vp2, 0x80
    vpop vp8, vp1, vp2, vp2, 0x02
    @vp6 vaddw vv6, vv5, vs0
    vpop vp4, vp4, vp6, vp6, 0xEE
    vpop vp1, vp1, vp6, vp6, 0x02
    @vp8 vadd vs18, vs19, vs0
    @vp8 vaddw vv4, vv5, vs0
    @vp8 vcjal 1, vs14, .Lpgain_kernel_loop4
    vpop vp1, vp4, vp4, vp4, 0xAA
    vpop vp1, vp1, vp5, vp5, 0xEE
    @vp5 vaddw vv4, vs0, vs0
    @vp4 vaddw vv4, vv6, vs0
    @!vp1 vcjal 0, vs14, .Lpgain_kernel_skip5
    @vp1 vlw vv5, va0
    @vp1 vfmul.s vv5, vv4, vv5
    @vp1 vlw vv4, va1
    vaddw vs15, vs10, vs8
    @vp1 vmulw vv6, vs15, vv0
    vcmpflt.s vp2, vv5, vv4
.Lpgain_kernel_skip5:
    vpop vp4, vp1, vp2, vp2, 0x80
    vpop vp5, vp1, vp2, vp2, 0x02
    @!vp4 vcjal 0, vs14, .Lpgain_kernel_skip6
    vaddw vv7, vs11, vs0
    @vp4 vsb vv7, va2
    @vp4 vaddw vv7, vv6, vs10
    @vp4 vfsub.s vv8, vv5, vv4
    @vp4 vsll vv2, vv7, vs9
    @vp4 vsxw vv8, vs15, vv2
.Lpgain_kernel_skip6:
    @!vp5 vcjal 0, vs14, .Lpgain_kernel_skip7
    @vp5 vld vv2, va3
    @vp5 vsll vv2, vv2, vs12
    @vp5 vsra vv2, vv2, vs13
    @vp5 vlxw vv7, vs16, vv2
    @vp5 vaddw vv7, vv7, vv6
    @vp5 vfsub.s vv5, vv4, vv5
    @vp5 vsll vv2, vv7, vs9
    @vp5 vlxw vv4, vs15, vv2
    @vp5 vfadd.s vv5, vv5, vv4
    @vp5 vsxw vv5, vs15, vv2
.Lpgain_kernel_skip7:
    vpop vp1, vp5, vp5, vp5, 0xAA
    vpop vp1, vp1, vp4, vp4, 0xEE
    vpop vp1, vp1, vp3, vp3, 0xEE
    vstop

# ---- control threads (from llc) ----
	.file	"hwacha-ct"
	.text
	.globl	memset_kernel_ct                # -- Begin function memset_kernel_ct
	.p2align	2
	.type	memset_kernel_ct,@function
memset_kernel_ct:                       # @memset_kernel_ct
	.cfi_startproc
# %bb.0:                                # %entry
	li	a3, -1
	slli	a3, a3, 54
	addi	a3, a3, 33
	slli	a2, a2, 48
	slli	a3, a3, 9
	srai	a2, a2, 48
	#APP
	vsetcfg a3
	#NO_APP
	#APP
	vmcs vs1, a2
	#NO_APP
	beqz	a0, .LBB0_3
# %bb.1:                                # %stripmine.preheader
.Lpcrel_hi0:
	auipc	a2, %pcrel_hi(memset_kernel_wt)
	addi	a2, a2, %pcrel_lo(.Lpcrel_hi0)
.LBB0_2:                                # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	#APP
	vsetvl a3, a0
	#NO_APP
	#APP
	vmca va0, a1
	#NO_APP
	sub	a0, a0, a3
	#APP
	vf 0(a2)
	#NO_APP
	add	a1, a1, a3
	bnez	a0, .LBB0_2
.LBB0_3:                                # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end0:
	.size	memset_kernel_ct, .Lfunc_end0-memset_kernel_ct
	.cfi_endproc
                                        # -- End function
	.globl	pgain_kernel_ct                 # -- Begin function pgain_kernel_ct
	.p2align	2
	.type	pgain_kernel_ct,@function
pgain_kernel_ct:                        # @pgain_kernel_ct
	.cfi_startproc
# %bb.0:                                # %entry
	lw	t0, 16(sp)
	lui	t1, 1048534
	lw	t2, 0(sp)
	addi	t1, t1, -1033
	ld	t3, 8(sp)
	srli	t1, t1, 1
	not	t1, t1
	sext.w	a7, a7
	#APP
	vsetcfg t1
	#NO_APP
	#APP
	vmcs vs2, a7
	#NO_APP
	#APP
	vmcs vs3, t2
	#NO_APP
	#APP
	vmcs vs4, a2
	#NO_APP
	#APP
	vmcs vs5, t3
	#NO_APP
	li	a2, 1
	#APP
	vmcs vs6, a6
	#NO_APP
	#APP
	vmcs vs7, a2
	#NO_APP
	#APP
	vmcs vs8, a2
	#NO_APP
	li	a2, 2
	#APP
	vmcs vs9, a2
	#NO_APP
	#APP
	vmcs vs10, t0
	#NO_APP
	li	a2, 49
	li	a6, 32
	#APP
	vmcs vs11, a2
	#NO_APP
	#APP
	vmcs vs12, a6
	#NO_APP
	li	a2, 30
	li	a6, 4
	#APP
	vmcs vs13, a2
	#NO_APP
	#APP
	vmcs vs17, a6
	#NO_APP
	#APP
	vmcs vs15, a3
	#NO_APP
	#APP
	vmcs vs16, a4
	#NO_APP
	beqz	a0, .LBB1_3
# %bb.1:                                # %stripmine.preheader
	li	a2, 0
	addi	a3, a1, 16
.Lpcrel_hi1:
	auipc	a6, %pcrel_hi(pgain_kernel_wt)
	addi	a4, a1, 8
	addi	a6, a6, %pcrel_lo(.Lpcrel_hi1)
.LBB1_2:                                # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	#APP
	vsetvl a7, a0
	#NO_APP
	#APP
	vmca va0, a1
	#NO_APP
	#APP
	vmca va1, a3
	#NO_APP
	#APP
	vmca va2, a5
	#NO_APP
	#APP
	vmca va3, a4
	#NO_APP
	#APP
	vmcs vs1, a2
	#NO_APP
	#APP
	vf 0(a6)
	#NO_APP
	sub	a0, a0, a7
	slli	t0, a7, 3
	slli	t1, a7, 4
	add	a2, a2, a7
	add	t0, t1, t0
	add	a1, a1, t0
	add	a3, a3, t0
	add	a5, a5, a7
	add	a4, a4, t0
	bnez	a0, .LBB1_2
.LBB1_3:                                # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end1:
	.size	pgain_kernel_ct, .Lfunc_end1-pgain_kernel_ct
	.cfi_endproc
                                        # -- End function
	.section	".note.GNU-stack","",@progbits
