# generated by hwacha-cc from bfsvar/D.ll
# ---- worker threads (vector-fetch blocks) ----

    .text
    .align 3
    .globl BFS_1_wt
BFS_1_wt:
    vpset vp0
    veidx vv0
    vadd vv0, vv0, vs63
    vcmplt vp1, vv0, vs62
    vpop vp2, vp0, vp1, vp1, 0x80
    vpop vp3, vp0, vp1, vp1, 0x02
    @!vp2 vcjal 0, vs1, .LBFS_1_skip0
    @vp2 vlb vv1, va0
    vcmpeq vp1, vv1, vs0
.LBFS_1_skip0:
    vpop vp4, vp2, vp1, vp1, 0x80
    vpop vp5, vp2, vp1, vp1, 0x02
    @!vp5 vcjal 0, vs1, .LBFS_1_skip1
    vaddw vv1, vs0, vs0
    @vp5 vsb vv1, va0
.LBFS_1_skip1:
    vpop vp1, vp5, vp5, vp5, 0xAA
    vpop vp1, vp1, vp4, vp4, 0xEE
    vpop vp1, vp1, vp3, vp3, 0xEE
    vstop

    .text
    .align 3
    .globl BFS_2_wt
BFS_2_wt:
    vpset vp0
    veidx vv0
    vadd vv0, vv0, vs63
    vcmplt vp1, vv0, vs62
    vpop vp2, vp0, vp1, vp1, 0x80
    vpop vp3, vp0, vp1, vp1, 0x02
    @!vp2 vcjal 0, vs1, .LBFS_2_skip0
    @vp2 vlb vv1, va0
    vcmpeq vp1, vv1, vs0
.LBFS_2_skip0:
    vpop vp4, vp2, vp1, vp1, 0x80
    vpop vp5, vp2, vp1, vp1, 0x02
    @!vp5 vcjal 0, vs1, .LBFS_2_skip1
    vaddw vv1, vs61, vs0
    @vp5 vsb vv1, va1
    vaddw vv1, vs61, vs0
    @vp5 vsb vv1, va2
    vssb vs60, vs61
    vaddw vv1, vs0, vs0
    @vp5 vsb vv1, va0
.LBFS_2_skip1:
    vpop vp1, vp5, vp5, vp5, 0xAA
    vpop vp1, vp1, vp4, vp4, 0xEE
    vpop vp1, vp1, vp3, vp3, 0xEE
    vstop

# ---- control threads (from llc) ----
	.file	"hwacha-ct"
	.text
	.globl	BFS_1_ct                        # -- Begin function BFS_1_ct
	.p2align	2
	.type	BFS_1_ct,@function
BFS_1_ct:                               # @BFS_1_ct
	.cfi_startproc
# %bb.0:                                # %entry
	lui	a1, 1048566
	addi	a1, a1, 2045
	srli	a1, a1, 1
	not	a1, a1
	sext.w	a7, a7
	#APP
	vsetcfg a1
	#NO_APP
	#APP
	vmcs vs62, a7
	#NO_APP
	beqz	a0, .LBB0_7
# %bb.1:                                # %stripmine.preheader
	li	a1, 0
.Lpcrel_hi0:
	auipc	a2, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi2:
	auipc	a5, %pcrel_hi(BFS_1_wt)
.Lpcrel_hi1:
	auipc	a4, %pcrel_hi(hwacha_vl_short)
	addi	a5, a5, %pcrel_lo(.Lpcrel_hi2)
	j	.LBB0_3
.LBB0_2:                                # %stripmine
                                        #   in Loop: Header=BB0_3 Depth=1
	#APP
	vsetvl a6, a7
	#NO_APP
	ld	t0, %pcrel_lo(.Lpcrel_hi1)(a4)
	sltu	a7, a6, a7
	sub	a0, a0, a6
	or	a7, t0, a7
	sd	a7, %pcrel_lo(.Lpcrel_hi1)(a4)
	#APP
	vmca va0, a3
	#NO_APP
	#APP
	vmcs vs63, a1
	#NO_APP
	#APP
	vf 0(a5)
	#NO_APP
	add	a1, a1, a6
	add	a3, a3, a6
	beqz	a0, .LBB0_7
.LBB0_3:                                # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	a7, %pcrel_lo(.Lpcrel_hi0)(a2)
	mv	a6, a0
	beqz	a7, .LBB0_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB0_3 Depth=1
	mv	a6, a7
.LBB0_5:                                # %stripmine
                                        #   in Loop: Header=BB0_3 Depth=1
	mv	a7, a0
	bltu	a0, a6, .LBB0_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB0_3 Depth=1
	mv	a7, a6
	j	.LBB0_2
.LBB0_7:                                # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end0:
	.size	BFS_1_ct, .Lfunc_end0-BFS_1_ct
	.cfi_endproc
                                        # -- End function
	.globl	BFS_2_ct                        # -- Begin function BFS_2_ct
	.p2align	2
	.type	BFS_2_ct,@function
BFS_2_ct:                               # @BFS_2_ct
	.cfi_startproc
# %bb.0:                                # %entry
	lui	a6, 1048566
	addi	a6, a6, 2045
	srli	a6, a6, 1
	not	a6, a6
	#APP
	vsetcfg a6
	#NO_APP
	sext.w	a5, a5
	#APP
	vmcs vs62, a5
	#NO_APP
	li	a5, 1
	#APP
	vmcs vs61, a5
	#NO_APP
	#APP
	vmcs vs60, a4
	#NO_APP
	beqz	a0, .LBB1_7
# %bb.1:                                # %stripmine.preheader
	li	a4, 0
.Lpcrel_hi3:
	auipc	a5, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi5:
	auipc	a7, %pcrel_hi(BFS_2_wt)
.Lpcrel_hi4:
	auipc	a6, %pcrel_hi(hwacha_vl_short)
	addi	a7, a7, %pcrel_lo(.Lpcrel_hi5)
	j	.LBB1_3
.LBB1_2:                                # %stripmine
                                        #   in Loop: Header=BB1_3 Depth=1
	#APP
	vsetvl t0, t1
	#NO_APP
	ld	t2, %pcrel_lo(.Lpcrel_hi4)(a6)
	sltu	t1, t0, t1
	sub	a0, a0, t0
	or	t1, t2, t1
	sd	t1, %pcrel_lo(.Lpcrel_hi4)(a6)
	#APP
	vmca va0, a2
	#NO_APP
	#APP
	vmca va1, a1
	#NO_APP
	#APP
	vmca va2, a3
	#NO_APP
	#APP
	vmcs vs63, a4
	#NO_APP
	#APP
	vf 0(a7)
	#NO_APP
	add	a4, a4, t0
	add	a2, a2, t0
	add	a1, a1, t0
	add	a3, a3, t0
	beqz	a0, .LBB1_7
.LBB1_3:                                # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	t1, %pcrel_lo(.Lpcrel_hi3)(a5)
	mv	t0, a0
	beqz	t1, .LBB1_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB1_3 Depth=1
	mv	t0, t1
.LBB1_5:                                # %stripmine
                                        #   in Loop: Header=BB1_3 Depth=1
	mv	t1, a0
	bltu	a0, t0, .LBB1_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB1_3 Depth=1
	mv	t1, t0
	j	.LBB1_2
.LBB1_7:                                # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end1:
	.size	BFS_2_ct, .Lfunc_end1-BFS_2_ct
	.cfi_endproc
                                        # -- End function
	.type	hwacha_group_size,@object       # @hwacha_group_size
	.bss
	.weak	hwacha_group_size
	.p2align	3, 0x0
hwacha_group_size:
	.quad	0                               # 0x0
	.size	hwacha_group_size, 8

	.type	hwacha_vl_short,@object         # @hwacha_vl_short
	.weak	hwacha_vl_short
	.p2align	3, 0x0
hwacha_vl_short:
	.quad	0                               # 0x0
	.size	hwacha_vl_short, 8

	.section	".note.GNU-stack","",@progbits
